dist: trusty
language: node_js
node_js: lts/*
cache:
  npm: true
stages:
  - test
jobs:
  include:
    - stage: test
      before_deploy:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - git remote add -f pub https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git fetch pub $TRAVIS_BRANCH
        - git checkout $TRAVIS_BRANCH
      deploy:
        - provider: script
          script: npm run release
          skip_cleanup: true
          keep_history: true
          on:
            tags: false
            all_branches: true
            condition: '$TRAVIS_BRANCH =~ ^(master)$'
        - provider: script
          script: npm run release -- from-package
          skip_cleanup: true
          keep_history: true
          on:
            tags: false
            all_branches: true
            condition: '$TRAVIS_BRANCH =~ ^(master/republish)$'
